# Generated by Django 4.2.3 on 2023-09-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Cliente', models.CharField(max_length=40)),
                ('DNI_Cliente', models.IntegerField()),
                ('Numero_contacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Servicio', models.CharField(max_length=40)),
                ('Tipo_Servicio', models.CharField(max_length=20)),
                ('ID_Servicio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_evento', models.DateField()),
                ('Lugar_evento', models.CharField(max_length=50)),
                ('Seña', models.BooleanField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppStark.servicios')),
            ],
        ),
    ]
